var config = {
    logo: "",
    moreGame: "http://wx.xiaomaichang.net",
    complaintsAddress: "http://www.xiaomaichang.net/other/complain",
    HeadImage: new egret.Texture(),
    nickName: "",
    width: 1080,
    height: 1920,
    pigX: 300,
    pigDeviation: 10,
    initHeight: 288,
    jumpHeight: 400,
    jumpCount: 2,
    jumpMaxGroundDeviation: 100,
    jumpGroundDeviation: 250,
    groundInit: 520,
    groundXmax: 1006,
    groundXmin: 450,
    groundYmax: 600,
    groundYmin: 312,
    monsterYmax: 950,
    monsterYmin: 700,
    distance: 500,
    dragonShowTime: 2500,
    dragonStartTime: 5000,
    balloonMax: 254,
    balloonMin: 520,
    balloonX: 200,
    goidMax: 500,
    lotteryCount: 5,
    lotteryTime: 300,
    lotteryAngle: 30,
    probabilityLogo: 0.1,
    goidUpTurn: 0.7,
    goidDownTurn: 0.3,
    goidTopPos: 100 // 金币抛物线额外高度
};
